### ISSUE TITLE
uuid:get_v4_urandom() always returns these results the first four times it is called

### ISSUE THREAD

**Issue by iambumblehead** [okeuday/uuid#12]
uuid:get_v4_urandom()  _always_ returns these results the first four times it is called:
```
 info {"01056c26-74c1-49f9-9c40-5162c8c7c1aa",
       "3bc859b2-3174-4b3c-986a-52a95f8175f7",
       "50c84cda-e011-49d3-889a-0b2ad8206e6c",
       "774129ae-db15-431e-9ded-fbfb924b33b2"}
```
The expected result:
 uuid:get_v4_urandom() should return a different random unique number

Reproduce this by cloning this repository and running rebar eunit: https://github.com/iambumblehead/edtsredunderline#uuid, try running rebar eunit several times and see if the result is the same each time for you as well.

I'm unsure exactly which circumstances cause this. I found it while trying to understand failing eunit tests around uuid and so I added an eunit test here to reproduce.

My system:
 Ubuntu, Erlang/OTP 17 [erts-6.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by okeuday** [comment]
As mentioned on IRC, urandom is referring to using the Erlang/OTP random module which provides a pseudo-random number sequence.  When the random module doesn't get seeded, that is the behavior you would see.  To seed, use code like http://news.yahoo.com/ignore-common-awful-career-advice-152610923.html .  It is better to use stronger randomness with uuid:get_v4/0 though it causes more latency.
