### ISSUE TITLE
Doesn't build on Erlang 18

### ISSUE THREAD

**Issue by lpgauth** [okeuday/uuid#13]
Doesn't build on Erlang 18 because of compile option warnings_as_errors.

    compile: warnings being treated as errors
    src/uuid.erl:1192: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
    make: *** [ebin/uuid.app] Error 1

**Comment by okeuday** [comment]
nowarn_deprecated_function should prevent that in the rebar.config.  If you are using erlang.mk, please add the change there, in a way that matches the rebar.config.

**Comment by lpgauth** [comment]
Errr, my bad, got it working. Thanks!
