### ISSUE TITLE
warning_as_errors needs to be overridden when uuid is a dependency

### ISSUE THREAD

**Issue by AeroNotix** [okeuday/uuid#19]
Consider removing `warning_as_errors` as the erl_opts needs to be overridden if an application is using uuid as a dependency.

**Comment by okeuday** [comment]
What warning is the problem?

**Comment by AeroNotix** [comment]
Sorry, here: 

"Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information."

**Comment by okeuday** [comment]
That warning only occurs if `ERLANG_OTP_VERSION_17` or `ERLANG_OTP_VERSION_16` is defined, so just make sure you have the proper define for your version of Erlang (e.g., https://github.com/okeuday/uuid/blob/master/rebar.config#L6-L9).

**Comment by AeroNotix** [comment]
Indeed, you can do that (which is what I am doing with an override) but in general should a dependency which doesn't provide much beyond utility rather than a whole application be specifying `warning_as_errors`?

**Comment by okeuday** [comment]
Yes, it is commonly used to avoid problems in the source code
