### ISSUE TITLE
Not an issue but a question to use with Elixir

### ISSUE THREAD

**Issue by ndrean** [okeuday/uuid#31]
How could I use this as a dependency in Elixir?

**Comment by okeuday** [comment]
@ndrean the `hex.pm` file needs the package name `uuid_erl`, as shown at https://github.com/CloudI/cloudi_core/blob/a2ee4e61edf3b4142e8ccb7eff2fab2ffdac1576/mix.exs#L34-L55 .  Otherwise, it is normal function calls like `:uuid.get_v4()`
